jobs:
- name: bootstrap-terraform-state
  plan:
  - get: pcf-pipelines
  - file: pcf-pipelines/tasks/create-initial-terraform-state/task.yml
    params:
      AWS_ACCESS_KEY_ID: {{TF_VAR_aws_access_key}}
      AWS_SECRET_ACCESS_KEY: {{TF_VAR_aws_secret_key}}
      S3_BUCKET_TERRAFORM: {{S3_OUTPUT_BUCKET}}
      S3_ENDPOINT: {{S3_ENDPOINT}}
      S3_REGION: {{TF_VAR_aws_region}}
    task: create-terraform-state
  serial_groups:
  - terraform
- name: create-infrastructure
  plan:
  - aggregate:
    - get: pcf-pipelines
    - get: terraform-state
    - get: pivnet-opsmgr
      params:
        globs:
        - '*AWS.yml'
  - config:
      image_resource:
        source:
          repository: czero/cflinuxfs2
        type: docker-image
      inputs:
      - name: pivnet-opsmgr
      outputs:
      - name: ami
      params:
        REGION: null
      platform: linux
      run:
        args:
        - -c
        - |
          ami=$(grep $REGION pivnet-opsmgr/*.yml | cut -d' ' -f2)
          echo $ami > ami/ami
        path: bash
    params:
      REGION: {{TF_VAR_aws_region}}
    task: find-ami
  - ensure:
      params:
        file: terraform-state-output/terraform.tfstate
      put: terraform-state
    file: pcf-pipelines/install-pcf/aws/tasks/prepare-aws/task.yml
    params:
      DB_MASTER_PASSWORD: {{db_master_password}}
      DB_MASTER_USERNAME: {{db_master_username}}
      OPSMAN_ALLOW_HTTPS_CIDR_RANGES: {{opsman_allow_https_cidr_ranges}}
      OPSMAN_ALLOW_SSH_CIDR_RANGES: {{opsman_allow_ssh_cidr_ranges}}
      TERRAFORM_PREFIX: {{terraform_prefix}}
      TF_VAR_amis_nat: {{TF_VAR_amis_nat}}
      TF_VAR_aws_access_key: {{TF_VAR_aws_access_key}}
      TF_VAR_aws_cert_arn: {{TF_VAR_aws_cert_arn}}
      TF_VAR_aws_key_name: {{TF_VAR_aws_key_name}}
      TF_VAR_aws_region: {{TF_VAR_aws_region}}
      TF_VAR_aws_secret_key: {{TF_VAR_aws_secret_key}}
      TF_VAR_az1: {{TF_VAR_az1}}
      TF_VAR_az2: {{TF_VAR_az2}}
      TF_VAR_az3: {{TF_VAR_az3}}
      TF_VAR_dynamic_services_subnet_cidr_az1: {{TF_VAR_dynamic_services_subnet_cidr_az1}}
      TF_VAR_dynamic_services_subnet_cidr_az2: {{TF_VAR_dynamic_services_subnet_cidr_az2}}
      TF_VAR_dynamic_services_subnet_cidr_az3: {{TF_VAR_dynamic_services_subnet_cidr_az3}}
      TF_VAR_ert_subnet_cidr_az1: {{TF_VAR_ert_subnet_cidr_az1}}
      TF_VAR_ert_subnet_cidr_az2: {{TF_VAR_ert_subnet_cidr_az2}}
      TF_VAR_ert_subnet_cidr_az3: {{TF_VAR_ert_subnet_cidr_az3}}
      TF_VAR_infra_subnet_cidr_az1: {{TF_VAR_infra_subnet_cidr_az1}}
      TF_VAR_nat_ip_az1: {{TF_VAR_nat_ip_az1}}
      TF_VAR_nat_ip_az2: {{TF_VAR_nat_ip_az2}}
      TF_VAR_nat_ip_az3: {{TF_VAR_nat_ip_az3}}
      TF_VAR_opsman_ip_az1: {{TF_VAR_opsman_ip_az1}}
      TF_VAR_public_subnet_cidr_az1: {{TF_VAR_public_subnet_cidr_az1}}
      TF_VAR_public_subnet_cidr_az2: {{TF_VAR_public_subnet_cidr_az2}}
      TF_VAR_public_subnet_cidr_az3: {{TF_VAR_public_subnet_cidr_az3}}
      TF_VAR_rds_subnet_cidr_az1: {{TF_VAR_rds_subnet_cidr_az1}}
      TF_VAR_rds_subnet_cidr_az2: {{TF_VAR_rds_subnet_cidr_az2}}
      TF_VAR_rds_subnet_cidr_az3: {{TF_VAR_rds_subnet_cidr_az3}}
      TF_VAR_route53_zone_id: {{ROUTE_53_ZONE_ID}}
      TF_VAR_services_subnet_cidr_az1: {{TF_VAR_services_subnet_cidr_az1}}
      TF_VAR_services_subnet_cidr_az2: {{TF_VAR_services_subnet_cidr_az2}}
      TF_VAR_services_subnet_cidr_az3: {{TF_VAR_services_subnet_cidr_az3}}
      TF_VAR_vpc_cidr: {{TF_VAR_vpc_cidr}}
    task: create-infrastructure
  - file: pcf-pipelines/install-pcf/aws/tasks/prepare-rds/task.yml
    params:
      DB_ACCOUNTDB_PASSWORD: {{db_accountdb_password}}
      DB_ACCOUNTDB_USERNAME: {{db_accountdb_username}}
      DB_APP_USAGE_SERVICE_PASSWORD: {{db_app_usage_service_password}}
      DB_APP_USAGE_SERVICE_USERNAME: {{db_app_usage_service_username}}
      DB_AUTOSCALE_PASSWORD: {{db_autoscale_password}}
      DB_AUTOSCALE_USERNAME: {{db_autoscale_username}}
      DB_CCDB_PASSWORD: {{db_ccdb_password}}
      DB_CCDB_USERNAME: {{db_ccdb_username}}
      DB_DIEGO_PASSWORD: {{db_diego_password}}
      DB_DIEGO_USERNAME: {{db_diego_username}}
      DB_LOCKET_PASSWORD: {{db_locket_password}}
      DB_LOCKET_USERNAME: {{db_locket_username}}
      DB_NETWORKPOLICYSERVERDB_PASSWORD: {{db_networkpolicyserverdb_password}}
      DB_NETWORKPOLICYSERVERDB_USERNAME: {{db_networkpolicyserverdb_username}}
      DB_NFSVOLUMEDB_PASSWORD: {{db_nfsvolumedb_password}}
      DB_NFSVOLUMEDB_USERNAME: {{db_nfsvolumedb_username}}
      DB_NOTIFICATIONS_PASSWORD: {{db_notifications_password}}
      DB_NOTIFICATIONS_USERNAME: {{db_notifications_username}}
      DB_ROUTING_PASSWORD: {{db_routing_password}}
      DB_ROUTING_USERNAME: {{db_routing_username}}
      DB_SILK_PASSWORD: {{db_silk_password}}
      DB_SILK_USERNAME: {{db_silk_username}}
      DB_UAA_PASSWORD: {{db_uaa_password}}
      DB_UAA_USERNAME: {{db_uaa_username}}
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      PEM: {{PEM}}
    task: prepare-rds
  serial_groups:
  - terraform
- name: configure-director
  plan:
  - aggregate:
    - get: pcf-pipelines
    - get: terraform-state
      passed:
      - create-infrastructure
      trigger: true
  - file: pcf-pipelines/tasks/config-opsman/task.yml
    params:
      OM_DECRYPTION_PWD: {{OPSMAN_PASSWORD}}
      OPS_MGR_PWD: {{OPSMAN_PASSWORD}}
      OPS_MGR_USR: {{OPSMAN_USER}}
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
    task: config-opsman-auth
  - file: pcf-pipelines/install-pcf/aws/tasks/config-director/task.yml
    params:
      AWS_KEY_NAME: {{TF_VAR_aws_key_name}}
      AWS_REGION: {{TF_VAR_aws_region}}
      ERT_DOMAIN: {{ERT_DOMAIN}}
      OPSMAN_PASSWORD: {{OPSMAN_PASSWORD}}
      OPSMAN_USER: {{OPSMAN_USER}}
      PEM: {{PEM}}
      S3_ENDPOINT: {{S3_ENDPOINT}}
      TRUSTED_CERTIFICATES: {{director_certificates}}
      dynamic_services_subnet_reserved_ranges_z1: {{dynamic_services_subnet_reserved_ranges_z1}}
      dynamic_services_subnet_reserved_ranges_z2: {{dynamic_services_subnet_reserved_ranges_z2}}
      dynamic_services_subnet_reserved_ranges_z3: {{dynamic_services_subnet_reserved_ranges_z3}}
      ert_subnet_reserved_ranges_z1: {{ert_subnet_reserved_ranges_z1}}
      ert_subnet_reserved_ranges_z2: {{ert_subnet_reserved_ranges_z2}}
      ert_subnet_reserved_ranges_z3: {{ert_subnet_reserved_ranges_z3}}
      infra_subnet_reserved_ranges_z1: {{infra_subnet_reserved_ranges_z1}}
      services_subnet_reserved_ranges_z1: {{services_subnet_reserved_ranges_z1}}
      services_subnet_reserved_ranges_z2: {{services_subnet_reserved_ranges_z2}}
      services_subnet_reserved_ranges_z3: {{services_subnet_reserved_ranges_z3}}
    task: configure-director
  serial_groups:
  - opsman
- name: deploy-director
  plan:
  - aggregate:
    - get: pcf-pipelines
    - get: terraform-state
      passed:
      - configure-director
      trigger: true
  - file: pcf-pipelines/tasks/apply-changes/task.yml
    params:
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      OPSMAN_PASSWORD: {{OPSMAN_PASSWORD}}
      OPSMAN_USERNAME: {{OPSMAN_USER}}
    task: deploy-director
  serial_groups:
  - opsman
- name: upload-ert
  plan:
  - aggregate:
    - get: pcf-pipelines
    - get: pivnet-product
      params:
        globs:
        - '*pivotal'
      resource: pivnet-elastic-runtime
    - get: terraform-state
      passed:
      - deploy-director
      trigger: true
  - file: pcf-pipelines/tasks/upload-product-and-stemcell/task.yml
    params:
      IAAS: aws
      NO_PROXY: ""
      OM_IP: ""
      OPS_MGR_PWD: {{OPSMAN_PASSWORD}}
      OPS_MGR_USR: {{OPSMAN_USER}}
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      PIVNET_API_TOKEN: {{pivnet_token}}
    task: upload-tile
  - file: pcf-pipelines/tasks/stage-product/task.yml
    params:
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      OPSMAN_PASSWORD: {{OPSMAN_PASSWORD}}
      OPSMAN_USERNAME: {{OPSMAN_USER}}
      PRODUCT_NAME: cf
    task: stage-tile
  serial_groups:
  - opsman
- name: deploy-ert
  plan:
  - aggregate:
    - get: pcf-pipelines
    - get: terraform-state
      passed:
      - upload-ert
      trigger: true
  - file: pcf-pipelines/tasks/configure-ert/task.yml
    params:
      MYSQL_BACKUPS: {{mysql_backups}}
      MYSQL_BACKUPS_S3_ACCESS_KEY_ID: {{mysql_backups_s3_access_key_id}}
      MYSQL_BACKUPS_S3_BUCKET_NAME: {{mysql_backups_s3_bucket_name}}
      MYSQL_BACKUPS_S3_BUCKET_PATH: {{mysql_backups_s3_bucket_path}}
      MYSQL_BACKUPS_S3_CRON_SCHEDULE: {{mysql_backups_s3_cron_schedule}}
      MYSQL_BACKUPS_S3_ENDPOINT_URL: {{mysql_backups_s3_endpoint_url}}
      MYSQL_BACKUPS_S3_SECRET_ACCESS_KEY: {{mysql_backups_s3_secret_access_key}}
      MYSQL_BACKUPS_SCP_CRON_SCHEDULE: {{mysql_backups_scp_cron_schedule}}
      MYSQL_BACKUPS_SCP_DESTINATION: {{mysql_backups_scp_destination}}
      MYSQL_BACKUPS_SCP_KEY: {{mysql_backups_scp_key}}
      MYSQL_BACKUPS_SCP_PORT: {{mysql_backups_scp_port}}
      MYSQL_BACKUPS_SCP_SERVER: {{mysql_backups_scp_server}}
      MYSQL_BACKUPS_SCP_USER: {{mysql_backups_scp_user}}
      OPS_MGR_PWD: {{OPSMAN_PASSWORD}}
      OPS_MGR_USR: {{OPSMAN_USER}}
      S3_ENDPOINT: {{S3_ENDPOINT}}
      azure_access_key: null
      azure_account_name: null
      azure_buildpacks_container: null
      azure_droplets_container: null
      azure_packages_container: null
      azure_resources_container: null
      db_accountdb_password: {{db_accountdb_password}}
      db_accountdb_username: {{db_accountdb_username}}
      db_app_usage_service_password: {{db_app_usage_service_password}}
      db_app_usage_service_username: {{db_app_usage_service_username}}
      db_autoscale_password: {{db_autoscale_password}}
      db_autoscale_username: {{db_autoscale_username}}
      db_ccdb_password: {{db_ccdb_password}}
      db_ccdb_username: {{db_ccdb_username}}
      db_diego_password: {{db_diego_password}}
      db_diego_username: {{db_diego_username}}
      db_locket_password: {{db_locket_password}}
      db_locket_username: {{db_locket_username}}
      db_networkpolicyserverdb_password: {{db_networkpolicyserverdb_password}}
      db_networkpolicyserverdb_username: {{db_networkpolicyserverdb_username}}
      db_nfsvolumedb_password: {{db_nfsvolumedb_password}}
      db_nfsvolumedb_username: {{db_nfsvolumedb_username}}
      db_notifications_password: {{db_notifications_password}}
      db_notifications_username: {{db_notifications_username}}
      db_routing_password: {{db_routing_password}}
      db_routing_username: {{db_routing_username}}
      db_silk_password: {{db_silk_password}}
      db_silk_username: {{db_silk_username}}
      db_uaa_password: {{db_uaa_password}}
      db_uaa_username: {{db_uaa_username}}
      gcp_storage_access_key: null
      gcp_storage_secret_key: null
      mysql_monitor_recipient_email: {{mysql_monitor_recipient_email}}
      pcf_az_1: {{TF_VAR_az1}}
      pcf_az_2: {{TF_VAR_az2}}
      pcf_az_3: {{TF_VAR_az3}}
      pcf_ert_domain: {{ERT_DOMAIN}}
      pcf_ert_networking_pointofentry: null
      pcf_ert_saml_cert: null
      pcf_ert_saml_key: null
      pcf_ert_ssl_cert: {{ERT_SSL_CERT}}
      pcf_ert_ssl_key: {{ERT_SSL_KEY}}
      pcf_iaas: aws
      terraform_prefix: {{terraform_prefix}}
    task: configure-ert
  - file: pcf-pipelines/tasks/disable-errands/task.yml
    params:
      ERRANDS_TO_DISABLE: {{ert_errands_to_disable}}
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      OPSMAN_PASSWORD: {{OPSMAN_PASSWORD}}
      OPSMAN_USERNAME: {{OPSMAN_USER}}
      PRODUCT_NAME: cf
    task: disable-errands
  - file: pcf-pipelines/tasks/apply-changes/task.yml
    params:
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      OPSMAN_PASSWORD: {{OPSMAN_PASSWORD}}
      OPSMAN_USERNAME: {{OPSMAN_USER}}
    task: deploy-ert
  serial_groups:
  - opsman
- ensure:
    params:
      file: terraform-state/terraform.tfstate
    put: terraform-state
  name: wipe-env
  plan:
  - aggregate:
    - get: pcf-pipelines
    - get: terraform-state
  - file: pcf-pipelines/install-pcf/aws/tasks/wipe-env/task.yml
    params:
      AWS_ACCESS_KEY_ID: {{TF_VAR_aws_access_key}}
      AWS_REGION: {{TF_VAR_aws_region}}
      AWS_SECRET_ACCESS_KEY: {{TF_VAR_aws_secret_key}}
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      OPSMAN_PASSWORD: {{OPSMAN_PASSWORD}}
      OPSMAN_USERNAME: {{OPSMAN_USER}}
    task: wipe
  serial_groups:
  - terraform
resource_types:
- name: pivnet
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final
  type: docker-image
resources:
- name: terraform-state
  source:
    access_key_id: {{TF_VAR_aws_access_key}}
    bucket: {{S3_OUTPUT_BUCKET}}
    disable_ssl: false
    endpoint: {{S3_ENDPOINT}}
    secret_access_key: {{TF_VAR_aws_secret_key}}
    versioned_file: terraform.tfstate
  type: s3
- name: pivnet-elastic-runtime
  source:
    api_token: {{pivnet_token}}
    product_slug: elastic-runtime
    product_version: {{ert_major_minor_version}}
    sort_by: semver
  type: pivnet
- name: pcf-pipelines
  source:
    uri: https://github.com/jigsheth57/pcf-pipelines.git
  type: git
- name: pivnet-opsmgr
  source:
    api_token: {{pivnet_token}}
    product_slug: ops-manager
    product_version: {{opsman_major_minor_version}}
    sort_by: semver
  type: pivnet
