resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: pivnet-rabbitmq
  type: pivnet
  source:
    api_token: {{pivnet_token}}
    product_slug: p-rabbitmq
    product_version: {{rmq_major_minor_version}}
    sort_by: semver

- name: pcf-pipelines
  type: git
  source:
    uri: https://github.com/jigsheth57/pcf-pipelines.git

jobs:
- name: upload-rmq
  serial_groups: [opsman]
  plan:
  - aggregate:
    - get: pcf-pipelines
    - get: pivnet-product
      resource: pivnet-rabbitmq
      params:
        globs:
        - "p-rabbitmq*.pivotal"
  - task: upload-tile
    file: pcf-pipelines/tasks/upload-product-and-stemcell/task.yml
    params:
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      OPSMAN_CLIENT_ID: ""
      OPSMAN_CLIENT_SECRET: ""
      OPS_MGR_USR: {{opsman_admin_username}}
      OPS_MGR_PWD: {{opsman_admin_password}}
      PIVNET_API_TOKEN: {{pivnet_token}}
      IAAS: "google"
      NO_PROXY: ""
      OM_IP: ""
  - task: stage-tile
    file: pcf-pipelines/tasks/stage-product/task.yml
    params:
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      OPSMAN_CLIENT_ID: ""
      OPSMAN_CLIENT_SECRET: ""
      OPSMAN_USERNAME: {{opsman_admin_username}}
      OPSMAN_PASSWORD: {{opsman_admin_password}}
- name: deploy-rmq
  serial_groups: [opsman]
  plan:
  - aggregate:
    - get: pcf-pipelines
      trigger: true
      passed: [upload-rmq]

  - task: configure-rmq
    file: pcf-pipelines/install-rmq/tasks/configure-rmq/task.yml
    params:
      pcf_az_1: {{gcp_zone_1}}
      pcf_az_2: {{gcp_zone_2}}
      pcf_az_3: {{gcp_zone_3}}
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      OPS_MGR_USR: {{opsman_admin_username}}
      OPS_MGR_PWD: {{opsman_admin_password}}
      INTERNET_CONNECTED: {{internet_connected}}
      SERVER_ADMIN_USERNAME: {{rmq_server_admin_username}}
      SERVER_ADMIN_PASSWORD: {{rmq_server_admin_password}}

  - task: disable-errands
    file: pcf-pipelines/tasks/disable-errands/task.yml
    params:
      PRODUCT_NAME: p-rabbitmq
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      OPSMAN_CLIENT_ID: ""
      OPSMAN_CLIENT_SECRET: ""
      OPSMAN_USERNAME: {{opsman_admin_username}}
      OPSMAN_PASSWORD: {{opsman_admin_password}}
      ERRANDS_TO_DISABLE: {{rmq_errands_to_disable}}

- name: apply-changes
  serial_groups: [opsman]
  plan:
  - aggregate:
    - get: pcf-pipelines
      trigger: false
      passed: [deploy-rmq]

  - task: apply-changes
    file: pcf-pipelines/tasks/apply-changes/task.yml
    params:
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      OPSMAN_CLIENT_ID: ""
      OPSMAN_CLIENT_SECRET: ""
      OPSMAN_USERNAME: {{opsman_admin_username}}
      OPSMAN_PASSWORD: {{opsman_admin_password}}
