---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: czero/rootfs

inputs:
- name: pcf-pipelines

run:
  path: pcf-pipelines/install-mysql/tasks/configure-mysql/task.sh

params:
  pcf_az_1:
  pcf_az_2:
  pcf_az_3:
  OPSMAN_DOMAIN_OR_IP_ADDRESS:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  INTERNET_CONNECTED:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  S3_BUCKET_BACKUP:
  S3_BUCKET_BACKUP_REGION:
  S3_BUCKET_BACKUP_PATH:
  S3_BUCKET_BACKUP_SCHEDULE:
