---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: czero/cflinuxfs2

inputs:
- name: pcf-pipelines

run:
  path: pcf-pipelines/tasks/configure-metrics/task.sh

params:
  pcf_ert_domain:
  OPSMAN_DOMAIN_OR_IP_ADDRESS:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  pcf_iaas:
  pcf_az_1:
  pcf_az_2:
  pcf_az_3:
  metrics_admin_id:
  metrics_admin_password:
